# Generated by Django 3.1.3 on 2020-11-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.TextField(unique=True)),
                ('status', models.CharField(choices=[('SCRAPING', 'Scraping'), ('WAITING', 'Waiting')], default='WAITING', max_length=10)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='database.job')),
                ('seen_results', models.ManyToManyField(to='database.Result')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='results',
            field=models.ManyToManyField(to='database.Result'),
        ),
    ]
